### ISSUE TITLE
[FEAT] Custom felt for contributors

### ISSUE THREAD

**Issue by eriktm** [gathering/unicorn-frontend#21]
Fra #support på Slack:
>Yo! Har ønske om et tekstfelt i Unicorn for at deltakarar skal kunne skrive inn minecraft brukarnamnet sitt, men ser kun muligheit for å få lasta opp submissions osv. Er det noko som kan bli ordna, eller ser eg på feil i new competitions sida?

Det finnes allerede et felt på contributors for extra info, men dette eksponeres ikke. Bør være mulig å definere på en konkurranse hva som må fylles inn i dette feltet og gjøre det obligatorisk å fylle ut.

**Comment by joms** [comment]
Lansert med 0bb51ac047a01250b4d6e8ef5619c18008c75aab
